/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.*;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame {
private  int puntos=0;
 private int dificultad;
    /**
     * Creates new form Main
     */
    public Main(int dificultad) {
        initComponents();
        int mul=0;
        if(dificultad==1){
            mul=1;
        }else if(dificultad==2){
            mul=10;
        }else if(dificultad==3){
            mul=100;
        }
        this.dificultad=mul;
        datosAleatorios();
    }
    public void agregarPuntos(){
        jLabel7.setText("Puntos: "+puntos);
    }
    public void datosAleatorios() {
        Random random = new Random();
        jTextFieldOp1.setText(random.nextInt(10*this.dificultad) + "");
        jTextFieldOp2.setText(random.nextInt(10*this.dificultad) + "");
        String operacion = "";
        int opcion = random.nextInt(4);
        switch (opcion) {
            case 0:
                jTextFieldOperacion.setText("*");
                break;
            case 1:
                jTextFieldOperacion.setText("+");
                break;
            case 2:
                jTextFieldOperacion.setText("-");
                break;
            case 3:
                jTextFieldOperacion.setText("/");
                break;

        }
        jTextFieldSol.setText("");
      //  realizarOperacion(opcion);
        jLabel4.setText("Resultado: "+realizarOperacion(opcion)+"");
        agregarPuntos();
        
    }
    public int realizarOperacion(int opcion){
        switch (opcion) {
            case 0:
               
                return Integer.parseInt(jTextFieldOp1.getText())*Integer.parseInt(jTextFieldOp2.getText());
                
            case 1:
                
                return Integer.parseInt(jTextFieldOp1.getText())+Integer.parseInt(jTextFieldOp2.getText());
                
            case 2:
                
                return Integer.parseInt(jTextFieldOp1.getText())-Integer.parseInt(jTextFieldOp2.getText());
                
            case 3:
                 return Integer.parseInt(jTextFieldOp1.getText())/Integer.parseInt(jTextFieldOp2.getText());

        }
        return -1000;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldOp1 = new javax.swing.JTextField();
        jTextFieldOp2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOperacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSol = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero 1:");

        jLabel2.setText("Numero 2:");

        jTextFieldOp1.setEditable(false);
        jTextFieldOp1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldOp2.setEditable(false);
        jTextFieldOp2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setText("Operacion:");

        jTextFieldOperacion.setEditable(false);
        jTextFieldOperacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Resuelto:");

        jLabel5.setText("Solución");

        jTextFieldSol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Continua");

        jLabel7.setText("Puntos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel7))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldSol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(jTextFieldOp2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldOperacion, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String opcion = jTextFieldOperacion.getText();
        int op=0;
        switch (opcion) {
            case "*":
                op=0;
                break;
            case "+":
                op=1;
                break;
            case "-":
                op=2;
                break;
            case "/":
                op=3;
                break;

        }
        int r1=realizarOperacion(op);
        int r2=Integer.parseInt(jTextFieldSol.getText());
        if(r1==r2){
            puntos++;
            datosAleatorios();
            jLabel6.setText("Continua");
        }else{
            jLabel6.setText("Has fallado");
        }
        agregarPuntos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldOp1;
    private javax.swing.JTextField jTextFieldOp2;
    private javax.swing.JTextField jTextFieldOperacion;
    private javax.swing.JTextField jTextFieldSol;
    // End of variables declaration//GEN-END:variables
}
